# a=int(input("Enter a number :"))
# b=int(input("Enter a number :"))
# print("Sum of entered numbers is : ",a+b)
# c=int(input("Enter  number :"))
# d=int(input("Enter  number :"))
# print ("Difference of entered numbers is :",c-d)
# e=int(input("Enter  number :"))
# f=int(input("Enter  number :"))
# print("Product of enterd numbers is :",e*f)
# g=int(input("Enter a number :"))
# h=int(input("Enter  number :"))
# print("Remainder is :",g%h)
# i=int(input("Enter number :"))
# j=int(input("Enter  number :"))
# print("Diviion of enterd numbers is :",i/j)


# list=[]
# a=int(input("Enter number here :"))
# list.append(a)
# b=int(input("Enter number here :"))
# list.append(b)
# c=int(input("Enter number here :"))
# list.append(c)
# d=int(input("Enter number here :"))
# list.append(d)
# e=int(input("Enter number here :"))
# list.append(e)
# print(max(list))

# a=int(input("Enter number to check wether it is positive  :"))
# print(a>0 )
# a=int(input("Enter number to check wether it is negative :"))
# print(a<0)
# a=int(input("Enter number to check wether it is zero :"))
# # print(a==0)
# list=[1,2,3,4]
# list.append("hasnian")
# print(list)

# a=int(input("Enter any desired number you want to check the type of data :"))
# print(type(a))
# a=float(input("Enter any desired number you want to check the type of data :"))
# print(type(a))
# a=input("Enter any desired number you want to check the type of data :")
# print(type(a))
# a=bool(input("Enter any desired number you want to check the type of data :"))
# print(type(a))

# a=int(input("Enter rollno here :"))
# list.append(a)
# b=int(input("Enter rollno here :"))
# list.append(b)
# c=int(input("Enter rollno here :"))
# list.append(c)
# d=int(input("Enter rollno here :"))
# list.append(d)
# e=int(input("Enter rollno here :"))
# list.append(e)
# print(list)

# list=[]
# a=int(input("Enter number here :"))
# list.append(a)
# b=int(input("Enter number here :"))
# list.append(b)
# c=int(input("Enter number here :"))
# list.append(c)
# d=int(input("Enter number here :"))
# list.append(d)
# e=int(input("Enter number here :"))
# list.append(e)
# print(list[0]%2==0)
# print(list[1]%2==0)
# print(list[2]%2==0)
# print(list[3]%2==0)
# print(list[4]%2==0)

# a = int(input("Enter number 1: "))
# b = int(input("Enter number 2: "))
# c = int(input("Enter number 3: "))
# d = int(input("Enter number 4: "))
# e = int(input("Enter number 5: "))

# lst = [a, b, c, d, e]

# print("Even numbers are:")
# print(lst[0] if lst[0] % 2 == 0 else "", )
# print(lst[1] if lst[1] % 2 == 0 else "", )
# print(lst[2] if lst[2] % 2 == 0 else "", )
# print(lst[3] if lst[3] % 2 == 0 else "", )
# print(lst[4] if lst[4] % 2 == 0 else "", )

list=[]
a=(input("Enter number here :"))
list.append(a)
b=(input("Enter number here :"))
list.append(b)
c=(input("Enter number here :"))
list.append(c)
d=(input("Enter number here :"))
list.append(d)
e=(input("Enter number here :"))

list.append(e)
print(list)